[project]
name = "search-ir-interview"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "supabase",
    "google-cloud-storage",
    "python-dotenv",
    "anthropic",
    "snowballstemmer>=3.1.1",
    "hnswlib>=0.8.0",
    "sentence-transformers>=5.6.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
